version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '84:80'
      - '82:81'
      - '444:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
